### ISSUE TITLE
Join Tables introduction should be moved earlier prior to initial usage

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/join-the-fun-rails#4]
For 000 batch (and possibly others), students need to utilize Join Tables before they actually encounter this lab. 

Specifically in the Forms and Validations section, probably starting with [Rails Blog Associations and Validations](https://github.com/learn-co-curriculum/rails-blog-associations-validations). In the current order, they are working with Join Tables without this initial instruction on them.

**Comment by AnnJohn** [comment]
Iceboxing this issue for now, and will reopen when we're reviewing that portion of the curriculum

**Comment by AnnJohn** [comment]
@pletcher not sure if this is still an open issue so if not, feel free to close

**Comment by pletcher** [comment]
It looks like it's been moved around in both the immersive track

<img width="287" alt="screen shot 2016-04-25 at 3 23 46 pm" src="https://cloud.githubusercontent.com/assets/2015049/14796137/c8bb3e38-0af9-11e6-9a77-403c156414f9.png">

and in v-000

<img width="283" alt="screen shot 2016-04-25 at 3 24 35 pm" src="https://cloud.githubusercontent.com/assets/2015049/14796159/e64b777e-0af9-11e6-9177-3d507ba9a291.png">
