### ISSUE TITLE
ERROR with rake db:migrate RAILS_ENV=test

### ISSUE THREAD

**Issue by jasterix** [learn-co-curriculum/join-the-fun-rails#7]
running rake db:migrate RAILS_ENV=test removes the foreign keys from the database schema

**Comment by micahshute** [comment]
Adding the appropriate migration which establishes the correct foreign keys in your tables is needed to set the necessary relationships in this lab - the migrations are not initially provided so you have to make them yourselves. If you do, the migrate command should work fine.

**Comment by jenmyers** [comment]
Hi there,

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab. Since it seems like this was an issue with the latter, closing for now.
